INSERT INTO USER VALUES (0, 'bla', 'ADMIN', 'blabla');
INSERT INTO CATEGORY VALUES (0, 'ART');
INSERT INTO CATEGORY VALUES (1, 'HOME');
INSERT INTO CATEGORY VALUES (2, 'TECH');
INSERT INTO CATEGORY VALUES (3, 'WOMEN');
INSERT INTO CATEGORY VALUES (4, 'MEN');
INSERT INTO PRODUCT VALUES (0, 'phone case', 1000);
INSERT INTO CATEGORY_PRODUCTS VALUES (2, 0);
INSERT INTO ORDERS VALUES (0, 1, '2017-08-09', FALSE, 0, 0);